Clang test
73s/Vorpal-Engine pull request #27
Opened 2017-01-25 11:27 UTC by Warezovvv

2017-01-25 11:29 UTC, Warezovvv commented on VorpalEngine/sources/video/Renderer.cpp
> +            || !CreateLogicalDevice()
говнясто выглядит это

2017-01-25 12:43 UTC, MrDmitry requested changes
Could you also try the SimpleStorageTest.cpp, I think we had some inconsistency with it the last time

2017-01-25 12:43 UTC, dsodintsov commented on VorpalEngine/sources/video/Renderer.cpp
> +        };
Just noticed that if scope ends with ; :100:

2017-01-25 12:43 UTC, dsodintsov commented on VorpalEngine/sources/video/Renderer.cpp
> +        m_graphicsPipeline = VK_NULL_HANDLE;
Not a huge fan of aligning operations. I prefer only comments, but that doesn't bother me much

2017-01-25 12:43 UTC, dsodintsov commented on VorpalEngine/sources/video/Renderer.cpp
> +            LOG_INFO("Vulkan render shutdown correctly.");
Force braces if possible

2017-01-25 12:43 UTC, dsodintsov commented on VorpalEngine/sources/video/Renderer.cpp
> +                                          std::min(capabilities.maxImageExtent.width, actualExtent.width));
Could you reset these split lines to just go to newline with addition indent? Not to the operands level

2017-01-25 12:43 UTC, dsodintsov commented on VorpalEngine/sources/video/Renderer.cpp
> +            = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT; // VK_IMAGE_USAGE_TRANSFER_DST_BIT for post processing.
That looks bad. Comment should've been transferred to the next line, not the assignment

2017-01-31 21:45 UTC, MrDmitry approved these changes

2017-01-31 22:22 UTC, merged